#  <font color='purple'>Linear ALgebra</font>
### THis is the linear and arithmatics in python



In [22]:
import numpy as np

#  <font color='purple'>Making Matrices</font>

In [25]:
###  first lets make a matrix


A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(A,B)

[[1 2 3]
 [4 5 6]] [[1 2 3]
 [4 5 6]
 [7 8 9]]


#  <font color='purple'>Matrix multiplication</font>

In [27]:
A @ B

array([[30, 36, 42],
       [66, 81, 96]])

#  <font color = "purple">Reshape Matrices</font>

In [5]:
b=np.random.randint(0,255,54880000)
image=np.reshape(b,(70000 , 28  , 28))
image

array([[[ 27, 101,  98, ...,  65, 243,  79],
        [106, 110, 248, ...,  53,  75, 120],
        [100, 249, 114, ..., 238, 179,  84],
        ...,
        [232, 219, 251, ..., 193,  85, 221],
        [129, 246,  50, ..., 193, 102,  87],
        [246,  10, 227, ...,  65,  44,  28]],

       [[  0, 231,  97, ..., 116, 236,   2],
        [171,  66,  92, ...,  85, 172,  16],
        [235, 223, 126, ...,  13, 103, 223],
        ...,
        [208, 110, 184, ..., 124, 236, 212],
        [134, 221,   0, ..., 217,  62, 183],
        [ 84, 225, 222, ...,  53, 241, 181]],

       [[ 93, 247,  63, ..., 215, 240, 208],
        [ 12, 254, 247, ...,  70,  85,   9],
        [ 68, 139,  69, ..., 115, 117,  33],
        ...,
        [159,  38,  47, ...,  61,  38,  69],
        [155, 227, 187, ..., 252, 241, 132],
        [157,  32,  16, ...,  88, 185,  59]],

       ...,

       [[227,  91, 202, ..., 150, 200, 227],
        [244, 164, 137, ..., 109, 146,  74],
        [ 95, 122, 101, ...,  56,  24, 133

# <font color = "purple">eigen values and eigenvectors</font>

In [6]:
import scipy.linalg as la 

A = np.array([[1., 1000], [0, 1]])
B = np.array([[1, 1000], [0.001, 1]])

print(A)

print(B)
A[0]

[[   1. 1000.]
 [   0.    1.]]
[[1.e+00 1.e+03]
 [1.e-03 1.e+00]]


array([   1., 1000.])

# <font color = "purple">we use scipy.linear algebra(linalg) library for linear algebra</font>

<font color = "blue">we use la.eig(A) for producing eig values and vectors</font>

In [7]:
np.set_printoptions(suppress=True, precision=4)

In [8]:
wA, vrA = la.eig(A)
wB, vrB = la.eig(B)

wA, wB , 

(array([1.+0.j, 1.+0.j]), array([2.+0.j, 0.+0.j]))

#  <font color='purple'>SVD</font>

In [9]:
import scipy.linalg as la
g=np.random.randint(0,255,30)
g=np.reshape(g,( 6  , 5))
g.shape

%time U, s, Vh = la.svd(g, full_matrices=False)

Wall time: 135 ms


In [10]:
reconstruvted_vectors = U @ np.diag(s) @ Vh


#  <font color='purple'>plot singular values</font>

In [28]:
import matplotlib.pyplot as plt
plt.plot(s)    # سینگولر ولیو ها از بزرگ هستند همین جور کوچک میشن 
%matplotlib inline

#  <font color='purple'>Norms</font>

###  <font color='blue'>You can change the norm by changing the ord</font>

In [12]:
norm  = np.linalg.norm(reconstruvted_vectors - g)
norm

5.052603395320109e-13

### <font color = "purple">numpy.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False).</font>

<font color = "purple">Returns True if two arrays are element-wise equal within a tolerance.</font>


#  <font color='purple'>Orthonormals</font>

In [29]:
y=(U@U.T).shape[0]
y
np.allclose(Vh@ Vh.T , np.eye(Vh.shape[0]) ) # np.eye is Identity matrix in shape of Vh@Vh.T  because vh should be row orthonormal

np.allclose(U.T@ U , np.eye(U.shape[1]) ) # np.eye is Identity matrix in shape of U.T@U  because U should be column orthonormal




True

In [30]:
np.set_printoptions(suppress=True) #این باعث میشه که اعشارای خیلی زیاد مثلا یک ضربدر ده به توان منفی 15 صفر بشه

In [31]:
U.T@ U

array([[ 1.,  0., -0., -0.,  0.],
       [ 0.,  1., -0., -0., -0.],
       [-0., -0.,  1.,  0., -0.],
       [-0., -0.,  0.,  1.,  0.],
       [ 0., -0., -0.,  0.,  1.]])

### <font color = "purple">نکات پایتونی</font>

In [32]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mydoubler

print(mydoubler(11))

22


### <font color = "purple"> numpy.argsort(a, axis=-1, kind=None, order=None)</font>
### <font color = "purple">Returns the indices that would sort an array.</font>



In [21]:
x = np.array([3, 1, 2])
np.argsort(x, axis=-1, kind=None, order=None)
np.argsort(x)

array([1, 2, 0], dtype=int64)

### <font color = "purple">numpy.where(condition,[x, y])</font>

##### <font color = "blue">Return elements chosen from x or y depending on condition.</font>

In [33]:
D = np.array([[2,3],
            [4,6],
            [8,9]])

In [34]:
D*D # عدد های متناطر رو در هم ضرب میکنه

array([[ 4,  9],
       [16, 36],
       [64, 81]])

#  <font color='purple'>How to save a matrix result and use it in future. (It's like saving deep learning results) </font>

In [35]:
import numpy as np
A = np.array([[1,2,3],
             [4,5,6]])
G = A*A

In [36]:
np.save("zarb A dar A" , G)  # وقتی عملات یه کار زیاده و نتیجشو میخوای نگه داری که وقتی فایلتو باز کردی اونو دگ لود نکنه

In [37]:
n =np.load("zarb A dar A.npy")
n

array([[ 1,  4,  9],
       [16, 25, 36]])